# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CitymapperUISample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CitymapperUISample

  # TODO: change to alpha once released
  pod 'CitymapperUI', '3.3.0-alpha.19'
  pod 'CitymapperGoogleSearchProvider', '3.3.0-alpha.19'

  target 'CitymapperUISampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CitymapperUISampleUITests' do
    # Pods for testing
  end

end
